DROP DATABASE IF EXISTS track_db;
CREATE DATABASE track_db;

USE track_db;

CREATE TABLE department (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dep_name VARCHAR(25) NOT NULL
);

CREATE TABLE role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(25) NOT NULL,
    dep_name VARCHAR(25) NOT NULL,
    salary DECIMAL (10)
);

CREATE TABLE employee (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL,
    title VARCHAR(25) NOT NULL,
    dep_name VARCHAR(25) NOT NULL,
    salary DECIMAL (10),
    manager VARCHAR(25)
);